### ISSUE TITLE
Run Report on Multiple Advertiser Accounts

### ISSUE THREAD

**Issue by ToddEvansHome** [BingAds/BingAds-dotNet-SDK#101]
When trying to run a performance report, using a Manager Account that contains 27 advertiser accounts, we receive the following error message: _"The specified report request contains at least one account which you have insufficient privileges to access. Please submit a report request for accounts that you are authorized to access."_

This is true for some of the accounts, but I believe that the report(s) should return data for all accounts that we do have access to under the Manager Account and ignore those accounts that we do not have access to.

This is how the MS Advertising website behaves.

So the question is, how can we run reports for a Manager Account that contains N number of advertiser accounts into 1 report.
Currently we have to run reports for each account separately.

**Comment by qitia** [comment]
discussed internally with the feature owner. below is their comments:

This has been debated a long time whether to throw error if user is requesting data for accounts it don’t have access to or return data for selected accounts it has access to.

We chose former approach here. 

Reason – agencies who manages multiple accounts must know their AccountId. They should send correct list rather than expecting API to filter out invalid AccountId. This is the best security practice followed.

Given customer has to run a report call for each accountId separately to know the list of Accounts it has to, they can use this list for next time.

I hope this answers your question.
